on:
  push:
    tags:    
      - "*"

jobs:
  build-proton-ge:
    runs-on: macos-10.15
    env:
      VAGRANT_CHECKPOINT_DISABLE: yes

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      
      - name: Install dependencies
        run: brew install coreutils
      - name: Show Vagrant version
        run: vagrant --version
      
      - name: Setup vbox additions
        run: vagrant plugin install vagrant-vbguest
      - name: apply patches
        run: ./patches/protonprep.sh

      - name: Run vagrant up
        run: vagrant up --no-tty
      - name: Run vagrant up
        run: vagrant up --no-tty

      - name: Build proton
        run: build_name=Proton-GE-${{ github.ref }} make redist
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_PAT }}
          file: vagrant_share/*
          tag: ${{ github.ref }}
          overwrite: false