on:
  push:
    tags:    
      - "*"

jobs:
  build-proton-ge:
    runs-on: macos-10.15
    # avoids hanging the system with vagrant checking for updates
    env:
      VAGRANT_CHECKPOINT_DISABLE: yes

    steps:
      - name: Install dependencies
        run: brew install coreutils
      # would be a shame to wait 2 hours for the
      # compilation to finish only to realise sha512sum is not
      # available
      - name: Test sha512sum availability
        run: echo "hello" | sha512sum
      
        - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Show Vagrant version
        run: vagrant --version
      
        # without this the share directory mounting fails
        # probably because the guest additions are old
      - name: Setup vbox additions
        run: vagrant plugin install vagrant-vbguest

      - name: apply patches
        run: ./patches/protonprep.sh

      - name: Run vagrant up
        run: vagrant up --no-tty
      - name: Run vagrant up
        run: vagrant up --no-tty

      # Build name following convention: Proton-GE-<tag>
      - name: Build proton
        run: build_name=Proton-GE-${{ github.ref }} make redist

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_PAT }}
          file: vagrant_share/*
          tag: ${{ github.ref }}
          overwrite: false